INSERT INTO public.permissions (key, label, description) VALUES
  ('access_to_dashboard', 'Accès au tableau de bord', 'Permet d''accéder au tableau de bord'),
  ('view_dashboard', 'Voir le tableau de bord', 'Permet de voir les statistiques du tableau de bord'),
  ('access_to_orders', 'Accès aux commandes', 'Permet d''accéder à la liste des commandes'),
  ('view_order', 'Voir une commande', 'Permet de voir les détails d''une commande'),
  ('create_order', 'Créer une commande', 'Permet de créer une nouvelle commande'),
  ('update_order', 'Modifier une commande', 'Permet de modifier une commande existante'),
  ('delete_order', 'Supprimer une commande', 'Permet de supprimer une commande'),
  ('show_all_orders', 'Voir toutes les commandes', 'Permet de voir les commandes de tous les vendeurs'),
  ('access_to_products', 'Accès aux produits', 'Permet d''accéder à la liste des produits'),
  ('view_product', 'Voir un produit', 'Permet de voir les détails d''un produit'),
  ('create_product', 'Créer un produit', 'Permet de créer un nouveau produit'),
  ('update_product', 'Modifier un produit', 'Permet de modifier un produit existant'),
  ('delete_product', 'Supprimer un produit', 'Permet de supprimer un produit'),
  ('show_all_products', 'Voir tous les produits', 'Permet de voir les produits de tous les vendeurs'),
  ('access_to_confirmations', 'Accès aux confirmations', 'Permet d''accéder à la liste des confirmations'),
  ('view_confirmation', 'Voir une confirmation', 'Permet de voir les détails d''une confirmation'),
  ('create_confirmation', 'Créer une confirmation', 'Permet de créer une nouvelle confirmation'),
  ('update_confirmation', 'Modifier une confirmation', 'Permet de modifier une confirmation existante'),
  ('show_all_confirmations', 'Voir toutes les confirmations', 'Permet de voir les confirmations de tous'),
  ('access_to_sellers', 'Accès aux vendeurs', 'Permet d''accéder à la liste des vendeurs'),
  ('view_seller', 'Voir un vendeur', 'Permet de voir les détails d''un vendeur'),
  ('show_seller_sales', 'Voir les ventes vendeur', 'Permet de voir les statistiques de ventes d''un vendeur'),
  ('access_to_users', 'Accès aux utilisateurs', 'Permet d''accéder à la gestion des utilisateurs'),
  ('create_user', 'Créer un utilisateur', 'Permet de créer un nouvel utilisateur'),
  ('update_user', 'Modifier un utilisateur', 'Permet de modifier un utilisateur existant'),
  ('delete_user', 'Supprimer un utilisateur', 'Permet de supprimer un utilisateur'),
  ('access_to_settings', 'Accès aux paramètres', 'Permet d''accéder aux paramètres'),
  ('access_to_analytics', 'Accès aux analytics', 'Permet d''accéder aux statistiques avancées'),
  ('access_to_integrations', 'Accès aux intégrations', 'Permet d''accéder aux intégrations'),
  ('access_to_invoices', 'Accès aux factures', 'Permet d''accéder aux factures'),
  ('access_to_sourcing', 'Accès au sourcing', 'Permet d''accéder aux demandes de sourcing')
ON CONFLICT (key) DO NOTHING;